[toolchain]
anchor_version = "0.28.0"

[features]
seeds = false
skip-lint = false

[programs.devnet]
cabal_protocol = "3jUomWjaKdsxzKt6Tn5DkzeAy3Yw686XDdT8dyWVeVmq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/unlonely-stream/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
