[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
cabal_protocol = "BMVB1Hx1xcHDujw2ScSxBit163Pke2MpjQWCVmd6YCoS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/unlonely-stream/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
